ingress-nginx:
  controller:
    replicaCount: 2
    nodeSelector:
      beta.kubernetes.io/os: linux
    admissionWebhooks:
      patch:
        nodeSelector:
          beta.kubernetes.io/os: linux
    service:
      loadBalancerIP: 52.232.101.84
      annotations:
        service.beta.kubernetes.io/azure-dns-label-name: dc6
  defaultBackend:
    nodeSelector:
      beta.kubernetes.io/os: linux
