ingress-nginx:
  controller:
    replicaCount: 2
    nodeSelector:
      "beta.kubernetes.io/os": linux
    admissionWebhooks:
      patch:
        nodeSelector:
          "beta.kubernetes.io/os": linux
#    service:
#      loadBalancerIP:
#      annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"="DNS_LABEL"
  defaultBackend:
    nodeSelector:
      "beta.kubernetes.io/os": linux
