kubernetes-external-secrets:
  env:
    AZURE_TENANT_ID:
      secretKeyRef: azure-credentials
      key: tenantid
    AZURE_CLIENT_ID:
      secretKeyRef: azure-credentials
      key: clientid
    AZURE_CLIENT_SECRET:
      secretKeyRef: azure-credentials
      key: clientsecret
