apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clouddns-prod
  labels:
    env: prod
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "bmalevich@rhg.com"
    privateKeySecretRef:
      name: "letsencrypt-prod"
    solvers:
      - dns01:
          cloudDNS:
            project: compute-impactlab
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
            hostedZoneName: cildev
