apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clouddns-dev
  labels:
    env: dev
spec:
  acme:
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: "mdelgado@rhg.com"
    privateKeySecretRef:
      name: "letsencrypt-dev"
    solvers:
      - dns01:
          cloudDNS:
            project: compute-impactlab
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
