apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.4.0/cert-manager.yaml
  - clouddns-dns01-solver-svc-acct-externalsecret.yaml
  - clouddns-prod-clusterissuer.yaml
  - clouddns-dev-clusterissuer.yaml

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: cert-manager
    path: patches/cert-manager-deployment.yaml
