apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflows-default-dask-rolebinding
subjects:
  - kind: ServiceAccount
    name: workflows-default
roleRef:
  kind: Role
  name: daskkubernetes
  apiGroup: rbac.authorization.k8s.io
